### ISSUE TITLE
Only first encrypted block is decrypted

### ISSUE THREAD

**Issue by jmiskovic** [eddiejessup/Transcrypt#10] opened 2017-01-27 11:59 UTC
If file consists of multiple parts that were encrypted separately, Transcrypt's decrypt command will decrypt only the first part and will silently discard the rest of content.

To reproduce the issue, start with following file:

> First line
> Second line

Select first line and encrypt using password "foo", then do the same for second line. The result is:

> +tjw5avPI5Tjihnh9fuFbA==
> dx3z28VMS+3BZ2n+nzC/mg==

If we now perform decrypt on whole file using same password, the second line is lost without warning:

> First line

Note that Crypto package refuses to decrypt this file, reporting that password is not correct. This is not ideal, but at least content is preserved.

BTW use case for this sequence is adding entries into existing encrypted journal

**Comment by eddiejessup** [comment] 2018-03-11 15:38
Hey, thanks for the detailed issue. However I can't reproduce this, can you try with the latest version, 1.3.0?

**Comment by jmiskovic** [comment] 2018-03-14 20:06
I just tried it again and it's still reproducible on my end. Only first line is decrypted and the second line is lost. I also checked in Package Manager, it's version 1.3.0.

**Comment by eddiejessup** [comment] 2018-09-11 07:51
I just got round to fixing this, sorry. It was a problem with base64 encoding (need to ask it to validate input). I pushed a version 1.4.0, see if that fixes things.

**Comment by eddiejessup** [comment] 2018-09-20 12:12
In the absence of a reply, I'm closing this since it now works for me. (Works, meaning it gives an error. I can't think of a more reasonable action in this situation.)

**Closed as completed by eddiejessup** 2018-09-20 12:12 UTC
