### ISSUE TITLE
Transcript doesn't change the selected text when I encrypt/decrypt

### ISSUE THREAD

**Issue by alex-hunsley-nl** [eddiejessup/Transcrypt#15] opened 2022-09-14 14:39 UTC
I'm using the latest version of this package on Mac OS on SublimeText 3 build 4126.

The package installs ok, and prompts for encryption or decryption passwords ok. It just doesn't then change the selection.

I have encrypted text which I'd like to access and can't decrypt. Can you help please?

**Comment by eddiejessup** [comment] 2022-09-14 17:34
Hi, I'll look into this now. are you using an arm or x86 mac? Ie an m1/m2/etc chip or intel?

**Comment by eddiejessup** [comment] 2022-09-14 22:14
Can you try running this script with your encoded file and password, then running the `openssl` command it outputs, to see if it works?

https://gist.github.com/eddiejessup/8de79e939b977e24491c9f26690c4c90

**Comment by yop1986** [comment] 2023-04-05 15:11
Hi there, do you have some information about this issue? Im having the same problem.

Windows 10 Pro 22H2
Sublime Text Stable Chanel Build 4143
Python-3.11.2-amd64 installed

I tried the gist to check if openssl, and get 
> openssl enc -aes-128-ecb -d -nosalt -nopad -base64 -A -in .\ -K 44617669643235353400000000000000

As an aditional information Sublime Console shows: 
Traceback (most recent call last):
File "C:\Users\xxxxx\AppData\Roaming\Sublime Text\Packages\Transcrypt\Crypto\Counter.py", line 3, in <module>
    from Transcrypt.Crypto import _counter
ImportError: DLL load failed: No se puede encontrar el módulo especificado.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\xxxxx\AppData\Roaming\Sublime Text\Packages\Transcrypt\Transcrypt.py", line 62, in init
    raise Exception("Can't load AES")
Exception: Can't load AES

I check and Packages\Transcrypt\Crypto\\_counter.pyd si there.

I have other computer with similar specifications and works correctly, do you have any idea.

Thanks for your time

**Comment by eddiejessup** [comment] 2023-04-06 09:02
Hey, what happens if you run the openssl command on the terminal?

**Comment by yop1986** [comment] 2023-04-07 05:15
Hi thanks for your reply, i tried

> python openssl_equiv_script.py test .

end the result was 

> openssl enc -aes-128-ecb -d -nosalt -nopad -base64 -A -in . -K 74657374000000000000000000000000

Is this what you need?

**Comment by eddiejessup** [comment] 2023-04-07 05:19
Hey, the idea is that the script outputs a command that you can then run in a terminal to decrypt your file. So if you open up a terminal and run that, you should get your decrypted result.

I see you're on Windows, I confess I don't know much about how Windows works nowadays, isn't there some Unix like terminal mode you can run commands in? But you might need to install openssl for it to work.

Anyway let me know if this makes any sense, try to run the command, and I'll help from whatever step we get to!

**Comment by yop1986** [comment] 2023-04-11 14:09
Thanks for your reply, 

I decrypt the file, but I would like to know if there is any chance to find what happend with the package "Transcrypt" in Sublime Text for Windows?

How can I validate what happedn with _counter?

Im really grateful for your support.

**Comment by eddiejessup** [comment] 2023-04-11 14:15
That's good to hear that you can decrypt the file, I don't want to leave you without access to the file!

To check I understand, do you mean you want to understand why the package isn't working, so we can fix it? If so, I can have a dig and probably won't be hard to find out what the problem is. But to be clear, I plan to deprecate the package when I get the time, since I no longer use sublime text so I don't have much motivation to maintain the package, and I'm nervous of leaving people with files they can't decrypt if the package breaks (like this situation). Happy to hear your thoughts on this.

**Comment by yop1986** [comment] 2023-04-11 15:00
Oh i got it, I usually use it so it would be great, but don't worry i understand. 

Thanks for all your time y really appreciate

**Comment by eddiejessup** [comment] 2023-04-12 07:28
No problem. Let's fix this issue, then you at least have a stable working version you can keep using after I remove the package from Package Control.

The import error that you're mentioning is probably related to the funky way we prepare those files: when the package first loads it inspects the current OS, and unzips the corresponding zip file containing pre-compiled binary files that are Python-callable. See here:

https://github.com/eddiejessup/Transcrypt/blob/master/Transcrypt.py#L39

First steps would be:

1. If you haven't already, can you install the package manually from this repo, rather than through package control? Basically you uninstall the current version you have, then `git clone` this repo into a `Packages/` folder under Sublime Text's install path. You can see detailed instructions [here](https://stackoverflow.com/a/71552379), look for 'Option 2 [what I prefer]: the command-line way'.
2. When you reinstall the package, if you open the console on ST startup you might see an error relating to the initial unzip step. If you do, let me know how it looks.
3. Can you open a Python terminal and run:

```python
import sys
print(sys.platform)
```

Just to check what branch of the logic we should expect to be running under?

**Comment by yop1986** [comment] 2023-04-12 15:16
Hi there, thanks for your time

I remember that already try to install the package manually, downloading from git and didn't work. I do it today and works perfectly, maybe I do something wrong before. 

I'm really thankful for helping me to understand how it works, it was a great package to me... 

I will keep following you, have a nice day.

**Comment by eddiejessup** [comment] 2023-04-13 05:50
Glad you fixed the problem! I'll close the issue

**Closed as completed** 2023-04-13 05:51 UTC
